version: 2
jobs:
  build:
    working_directory: ~/caffeination_be
    docker:
      - image: circleci/ruby:3.0.0
        environment:
          PGHOST: localhost
          PGUSER: caffeination_be
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: caffeination_be
          POSTGRES_DB: caffeination_be_test
          POSTGRES_PASSWORD: POSTGRES_HOST_AUTH_METHOD=trust
    dependencies:
    pre:
    - gem install bundler -v '2.2.3
    steps:
      # Setup environment
      - checkout
      - run: gem install bundler:2.2.3
      - run: bundle config set --local path 'projects/caffeination_rails/caffeination_be'
      - run: bundle install --path 'projects/caffeination_rails/caffeination_be'

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the database
      - run: bundle exec rails db:create
      - run: bundle exec rails db:migrate
      - run: bundle exec rails db:schema:load

      # Run the tests
      - run: bundle exec rspec
