version: 2
jobs:
  build:
    working_directory: ~/caffeination_fe
    docker:
      - image: circleci/ruby:3.0.0
        environment:
          PGHOST: localhost
          PGUSER: caffeination_fe
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: caffeination_fe
          POSTGRES_DB: caffeination_fe_test
          POSTGRES_PASSWORD: POSTGRES_HOST_AUTH_METHOD=trust
    dependencies:
    pre:
    - gem install bundler -v '2.2.3
    steps:
      # Setup environment
      - checkout
      - run: gem install bundler:2.2.3
      - run: bundle config set --local path 'projects/caffeination_rails/caffeination_fe'
      - run: bundle install --path 'projects/caffeination_rails/caffeination_fe'

      # Fix node errors with webpacker
      - run: bundle exec rails assets:precompile

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the database
      - run: bundle exec rails db:create
      - run: bundle exec rails db:migrate
      - run: bundle exec rails db:schema:load

      # Not running request specs!

      # Run the feature tests
      - run: bundle exec rspec spec/feature

      # Run the unit tests
      - run: bundle exec rspec spec/unit
